# Generated by Django 3.2.1 on 2021-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_bid_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='min_price',
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
